# Generated by Django 2.2.1 on 2019-05-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0003_user_matchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
