# Generated by Django 2.2.1 on 2019-05-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190511_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_location',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
